import { AccountType, BbeeLevel, EntityType, StepId } from "./types";

export const STEP_ORDER: StepId[] = [
  "welcome",
  "company",
  "contact",
  "directors",
  "references",
  "tax",
  "banking",
  "documents",
  "credit",
  "suretyship",
  "review",
  "confirmation",
];

// Steps that show the pill progress indicator (Review and the bookend
// Welcome/Confirmation screens are intentionally excluded).
export const DATA_STEPS: StepId[] = [
  "company",
  "contact",
  "directors",
  "references",
  "tax",
  "banking",
  "documents",
  "credit",
  "suretyship",
];

// South African entity types (CC and Pty Ltd are SA-specific legal structures).
export const ENTITY_TYPES: EntityType[] = ["(Pty) Ltd", "CC", "Sole Proprietor", "Partnership", "Trust"];

// Fallback structures for foreign entities registered in a country not listed in
// ENTITY_TYPES_BY_COUNTRY below.
export const FOREIGN_ENTITY_TYPES: string[] = [
  "Limited Company (Ltd/LLC)",
  "Public Company",
  "Sole Proprietor",
  "Partnership",
  "Trust",
  "Other",
];

// Country-specific legal entity structures for foreign entities, used in place of
// FOREIGN_ENTITY_TYPES when the selected country of registration has a known list.
export const ENTITY_TYPES_BY_COUNTRY: Record<string, string[]> = {
  "United States": ["LLC", "C-Corporation", "S-Corporation", "Sole Proprietorship", "Partnership", "Trust"],
  "United Kingdom": [
    "Private Limited Company (Ltd)",
    "Public Limited Company (PLC)",
    "Limited Liability Partnership (LLP)",
    "Sole Trader",
    "Partnership",
    "Trust",
  ],
  Australia: ["Proprietary Limited (Pty Ltd)", "Public Company", "Sole Trader", "Partnership", "Trust"],
  "New Zealand": ["Limited Company (Ltd)", "Sole Trader", "Partnership", "Trust"],
  Canada: ["Corporation (Inc./Ltd.)", "Sole Proprietorship", "Partnership", "Trust"],
  Germany: ["GmbH", "AG", "Sole Proprietorship", "Partnership (OHG/KG)", "Trust/Foundation"],
  India: [
    "Private Limited Company",
    "Public Limited Company",
    "Limited Liability Partnership (LLP)",
    "Sole Proprietorship",
    "Partnership",
    "Trust",
  ],
  Namibia: ["Pty Ltd", "CC", "Sole Proprietor", "Partnership", "Trust"],
  Botswana: ["Pty Ltd", "Sole Proprietor", "Partnership", "Trust"],
  Ireland: [
    "Private Company Limited by Shares (LTD)",
    "Public Limited Company (PLC)",
    "Sole Trader",
    "Partnership",
    "Trust",
  ],
  Singapore: ["Private Limited Company (Pte Ltd)", "Sole Proprietorship", "Partnership", "Trust"],
  "Hong Kong": ["Private Limited Company", "Sole Proprietorship", "Partnership", "Trust"],
  "United Arab Emirates": [
    "Limited Liability Company (LLC)",
    "Free Zone Company",
    "Sole Establishment",
    "Partnership",
    "Trust",
  ],
};

// Payment terms offered on the credit application step. "60 Days from statement" is
// listed but rejected at validation — see validateCredit in lib/validation.ts.
export const PAYMENT_TERMS_OPTIONS: string[] = [
  "Cash on Delivery",
  "7 Days from Delivery",
  "30 Days from statement",
  "60 Days from statement",
];

export const BBEE_LEVELS: BbeeLevel[] = [
  "Level 1",
  "Level 2",
  "Level 3",
  "Level 4",
  "Level 5",
  "Level 6",
  "Level 7",
  "Level 8",
  "Exempt",
  "Non-compliant",
];

export const ACCOUNT_TYPES: AccountType[] = ["Current/Cheque", "Savings"];

export const COUNTRIES: string[] = [
  "South Africa",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Guinea",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024;

export const ALLOWED_FILE_TYPES = ["application/pdf", "image/jpeg", "image/png"];

// Major South African banks and their universal (single, nationwide) branch
// codes. Used to auto-fill the branch code once a bank is picked, and as a
// safeguard against people typing a branch-specific code for a bank that
// actually uses one universal code. Not exhaustive — smaller/mutual banks
// aren't listed and the branch code field always stays manually editable.
export const SA_BANKS: { name: string; universalBranchCode: string }[] = [
  { name: "Absa Bank", universalBranchCode: "632005" },
  { name: "African Bank", universalBranchCode: "430000" },
  { name: "Bank Zero", universalBranchCode: "888000" },
  { name: "Bidvest Bank", universalBranchCode: "462005" },
  { name: "Capitec Bank", universalBranchCode: "470010" },
  { name: "Discovery Bank", universalBranchCode: "679000" },
  { name: "First National Bank (FNB)", universalBranchCode: "250655" },
  { name: "Investec Bank", universalBranchCode: "580105" },
  { name: "Mercantile Bank", universalBranchCode: "450905" },
  { name: "Nedbank", universalBranchCode: "198765" },
  { name: "Sasfin Bank", universalBranchCode: "683000" },
  { name: "Standard Bank", universalBranchCode: "051001" },
  { name: "TymeBank", universalBranchCode: "678910" },
  { name: "Ubank", universalBranchCode: "431010" },
];

// Major banks in the countries our foreign debtors bank with most often, with SWIFT/BIC
// codes for autofill. Not exhaustive and not a substitute for a universal branch-code
// style guarantee — there's no single standard internationally, so the field stays
// manually editable and users are told to double-check against their bank statement.
export const MAJOR_INTL_BANKS: { name: string; swift: string }[] = [
  { name: "HSBC (UK)", swift: "HBUKGB4B" },
  { name: "Barclays (UK)", swift: "BARCGB22" },
  { name: "Lloyds Bank (UK)", swift: "LOYDGB2L" },
  { name: "NatWest (UK)", swift: "NWBKGB2L" },
  { name: "Standard Chartered (UK)", swift: "SCBLGB2L" },
  { name: "Deutsche Bank (Germany)", swift: "DEUTDEFF" },
  { name: "Commerzbank (Germany)", swift: "COBADEFF" },
  { name: "BNP Paribas (France)", swift: "BNPAFRPP" },
  { name: "Societe Generale (France)", swift: "SOGEFRPP" },
  { name: "Citibank (USA)", swift: "CITIUS33" },
  { name: "JPMorgan Chase (USA)", swift: "CHASUS33" },
  { name: "Bank of America (USA)", swift: "BOFAUS3N" },
  { name: "Wells Fargo (USA)", swift: "WFBIUS6S" },
  { name: "Royal Bank of Canada", swift: "ROYCCAT2" },
  { name: "TD Bank (Canada)", swift: "TDOMCATTTOR" },
  { name: "ANZ Bank (Australia)", swift: "ANZBAU3M" },
  { name: "Commonwealth Bank (Australia)", swift: "CTBAAU2S" },
  { name: "Westpac (Australia)", swift: "WPACAU2S" },
];

export const STEP_TITLES: Partial<Record<StepId, string>> = {
  company: "Company details",
  contact: "Contact details",
  directors: "Directors & members",
  references: "Trade references",
  tax: "Tax & compliance",
  banking: "Banking details",
  documents: "Document uploads",
  credit: "Credit application terms",
  suretyship: "Suretyship agreement",
  review: "Review & declaration",
};
