import { AccountType, BbeeLevel, EntityType, StepId } from "./types";

export const STEP_ORDER: StepId[] = [
  "welcome",
  "company",
  "contact",
  "directors",
  "references",
  "tax",
  "banking",
  "documents",
  "credit",
  "review",
  "confirmation",
];

// Steps that show the pill progress indicator (Review and the bookend
// Welcome/Confirmation screens are intentionally excluded).
export const DATA_STEPS: StepId[] = [
  "company",
  "contact",
  "directors",
  "references",
  "tax",
  "banking",
  "documents",
  "credit",
];

// South African entity types (CC and Pty Ltd are SA-specific legal structures).
export const ENTITY_TYPES: EntityType[] = ["Pty Ltd", "CC", "Sole Proprietor", "Partnership", "Trust"];

// Generic structures for entities registered outside South Africa — CC and Pty Ltd
// don't apply here since those are SA-specific company types.
export const FOREIGN_ENTITY_TYPES: EntityType[] = [
  "Limited Company (Ltd/LLC)",
  "Public Company",
  "Sole Proprietor",
  "Partnership",
  "Trust",
  "Other",
];

export const BBEE_LEVELS: BbeeLevel[] = [
  "Level 1",
  "Level 2",
  "Level 3",
  "Level 4",
  "Level 5",
  "Level 6",
  "Level 7",
  "Level 8",
  "Exempt",
  "Non-compliant",
];

export const ACCOUNT_TYPES: AccountType[] = ["Current/Cheque", "Savings"];

export const COUNTRIES: string[] = [
  "South Africa",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Guinea",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024;

export const ALLOWED_FILE_TYPES = ["application/pdf", "image/jpeg", "image/png"];

// Major South African banks and their universal (single, nationwide) branch
// codes. Used to auto-fill the branch code once a bank is picked, and as a
// safeguard against people typing a branch-specific code for a bank that
// actually uses one universal code. Not exhaustive — smaller/mutual banks
// aren't listed and the branch code field always stays manually editable.
export const SA_BANKS: { name: string; universalBranchCode: string }[] = [
  { name: "Absa Bank", universalBranchCode: "632005" },
  { name: "African Bank", universalBranchCode: "430000" },
  { name: "Bank Zero", universalBranchCode: "888000" },
  { name: "Bidvest Bank", universalBranchCode: "462005" },
  { name: "Capitec Bank", universalBranchCode: "470010" },
  { name: "Discovery Bank", universalBranchCode: "679000" },
  { name: "First National Bank (FNB)", universalBranchCode: "250655" },
  { name: "Investec Bank", universalBranchCode: "580105" },
  { name: "Mercantile Bank", universalBranchCode: "450905" },
  { name: "Nedbank", universalBranchCode: "198765" },
  { name: "Sasfin Bank", universalBranchCode: "683000" },
  { name: "Standard Bank", universalBranchCode: "051001" },
  { name: "TymeBank", universalBranchCode: "678910" },
  { name: "Ubank", universalBranchCode: "431010" },
];

export const STEP_TITLES: Partial<Record<StepId, string>> = {
  company: "Company details",
  contact: "Contact details",
  directors: "Directors & members",
  references: "Trade references",
  tax: "Tax & compliance",
  banking: "Banking details",
  documents: "Document uploads",
  credit: "Credit application terms",
  review: "Review & declaration",
};
